### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by Pratyush2703**

### CODE REVIEW

**Comment by ankit-kumar-dwivedi** [comment]
Hi @Pratyush2703 I can see you added a CSV file. Are you going to add some explaination  about it? I suggest you stick with the guidelines.

**Comment by Pratyush2703** [comment]
Didn't mean to add the csv to the pull request yet (Not used to GIT since I mostly work on mercurial). I'll be updating and adding a pyspark based version of some algorithms over the next few days.

**Comment by ankit-kumar-dwivedi** [comment]
That's alright @Pratyush2703 will be waiting for your contribution:)

**Comment by ankit-kumar-dwivedi** [comment]
@Pratyush2703 marking it as invalid please open a new PR

**Pull request closed without merging**
